[build]
  command = "pnpm run build"
  publish = "dist/client"

[build.environment]
  NODE_VERSION = "22"

[dev]
  command = "pnpm run dev"
  targetPort = 3000
  port = 8888


[[redirects]]
  from = "/lawnbrain"
  to = "https://lawnbrain.base44.app/home?source=lawnladco"
  status = 302
  force = true

[[redirects]]
  from = "/scan"
  to = "https://lawnbrain.base44.app/register?source=lawnladco"
  status = 302
  force = true

[[redirects]]
  from = "/lawnleague"
  to = "https://lawnbrain.base44.app/league?source=lawnladco"
  status = 302
  force = true
